name: 'y'
favicon: null
layout_spectrum: 0.04818713944405317
typography_spectrum: 0.6523458058945835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7710660092998296
  lightness: 0.3395003811456263
  saturation: 0.26727502536959946
  rhythmicContrast: 0.024679251480847597
purpose: []
