title: Yves
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.375
  brandStrength: 0.4375
  rhythmicContrast: 0.5
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.375
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'y'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6523458058945835
layout_spectrum: 0.2222222
