name: 'y'
favicon: null
layout_spectrum: 0.1004
typography_spectrum: 0.6523458058945835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
